services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres-db
    networks:
      tryckers_network: {}

  postgres-db:
    image: postgres:15
    restart: always
    container_name: tryckers_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tryckers_network

volumes:
  pgdata: {}

networks:
  tryckers_network: {}
