


services:
  postgres-db:
    image: postgres:15
    restart: always
    container_name: tryckers_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
          tryckers_network: {}  

volumes:
  pgdata: {} 

networks:
  tryckers_network: {}  